### ISSUE TITLE
Hi, I got an exception

### ISSUE THREAD

**Issue by game-libgdx-unity** [fxdm92/kissanime#1]
First, Thanks for your work, then when I import you source, I try to download the selenium library

and got an exception:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Maps
    at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:45)
    at org.openqa.selenium.firefox.FirefoxProfile.<init>(FirefoxProfile.java:56)
    at main.main(main.java:33)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Maps
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 3 more

I think the downloaded jar causes the problem. Can you give me instruction for running the project?
Thanks
Vinh

**Comment by game-libgdx-unity** [comment]
I fixed the problem, thanks
